/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    GamePreview: typeof import('./components/GamePreview.vue')['default']
    ICarbonMobileViewOrientation: typeof import('~icons/carbon/mobile-view-orientation')['default']
    IEpCarbonMobileViewOrientation: typeof import('~icons/ep/carbon-mobile-view-orientation')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpMobileViewOrientation: typeof import('~icons/ep/mobile-view-orientation')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
