/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    GamePreview: typeof import('./components/GamePreview.vue')['default']
    ICarbonCloseFilled: typeof import('~icons/carbon/close-filled')['default']
    ICarbonDelete: typeof import('~icons/carbon/delete')['default']
    ICarbonMobileViewOrientation: typeof import('~icons/carbon/mobile-view-orientation')['default']
    ICarbonRenew: typeof import('~icons/carbon/renew')['default']
    ICarbonSearch: typeof import('~icons/carbon/search')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
